# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'win1803'

steps:
- script: docker build . --file Dockerfile -m 4GB --tag windows-cuda:v1.0.0
  displayName: 'Build the Docker image'
