# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Default
  timeoutInMinutes: 120

  pool:
    vmImage: 'win1803'

  steps:
  - script: |
      if not "%DOCKER_PASSWORD%" == "" docker login docker.pkg.github.com -u peterjc123 -p %DOCKER_PASSWORD%
      docker build . --file Dockerfile -m 4GB --isolation="process" --tag docker.pkg.github.com/peterjc123/windows-cuda-container/windows-cuda:v1.0.0
      if not "%DOCKER_PASSWORD%" == "" docker push docker.pkg.github.com/peterjc123/windows-cuda-container/windows-cuda:v1.0.0
    displayName: 'Build & Publish the Docker image'
    env:
      DOCKER_PASSWORD: $(pass)
