# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Default
  timeoutInMinutes: 120

  pool:
    vmImage: 'win1803'

  steps:
  - script: |
      # net stop docker
      # pushd C:\Program Files\Docker\Docker\resources
      # dockerd --unregister-service
      # dockerd --register-service --max-concurrent-uploads 1
      # popd
      # net start docker
      if not "%DOCKER_PASSWORD%" == "" docker login docker.pkg.github.com -u peterjc123 -p %DOCKER_PASSWORD%
      if errorlevel 1 exit /b 1
      powershell.exe -Command New-NetQosPolicy -Name "docker upload" -IPProtocol Both -AppPathNameMatchCondition dockerd.exe -ThrottleRateActionBitsPerSecond 5MB
      if errorlevel 1 exit /b 1
      docker build . --file Dockerfile -m 4GB --isolation="process" --tag docker.pkg.github.com/peterjc123/windows-cuda-container/windows-cuda:v1.0.0
      if errorlevel 1 exit /b 1
      if not "%DOCKER_PASSWORD%" == "" docker push docker.pkg.github.com/peterjc123/windows-cuda-container/windows-cuda:v1.0.0
      if errorlevel 1 exit /b 1
    displayName: 'Build & Publish the Docker image'
    env:
      DOCKER_PASSWORD: $(pass)
